### ISSUE TITLE
文档的问题（--api相关）

### ISSUE THREAD

**Issue by HideUsSaveUs** [wfjsw/VP-StableDiffusionBook#3]
用--api有可能会导致奇怪的错误，如   远程主机强迫关闭了一个现有的连接。  建议使用--nowebui

**Comment by HideUsSaveUs** [comment]
没仔细看，但是确实是要改一部分的，更新太快了

**Comment by HideUsSaveUs** [comment]
看了一下。如果使用--nowebui的话将会不启用webui。

**Comment by wfjsw** [comment]
没遇到过，有没有图啊

**Comment by wfjsw** [comment]
我觉得出这个错误大概率是启用了系统代理但是没有排除本机地址，这跟 API 应该没什么关系

**Comment by HideUsSaveUs** [comment]
可能得明天。因为今天晚上已经断电了:(

**Comment by HideUsSaveUs** [comment]
明天发一下

**Comment by HideUsSaveUs** [comment]
![image](https://user-images.githubusercontent.com/39188665/205418910-5647455b-d16e-422b-ad3f-b17ac81c9253.png)
如果用代码调用的话。

```
[Running] set PYTHONIOENCODING=utf8 && python "c:\Users\HideUsSaveUs\Desktop\1.py"
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000161CF401AB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7861): Max retries exceeded with url: /sdapi/v1/txt2img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000161CF401AB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\HideUsSaveUs\Desktop\1.py", line 35, in <module>
    WebUIApi(url="http://127.0.0.1:7861").txt2img(payload=payload,outpath="1145.png",infotie=True)
  File "c:\Users\HideUsSaveUs\Desktop\1.py", line 14, in txt2img
    response = requests.post(url=f'{self.url}/sdapi/v1/txt2img', data=payload_json).json()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7861): Max retries exceeded with url: /sdapi/v1/txt2img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000161CF401AB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

[Done] exited with code=1 in 2.851 seconds


```

**Comment by wfjsw** [comment]
这错误看起来很迷惑，基本上什么都没说。启动参数是什么？

**Comment by HideUsSaveUs** [comment]
--opt-split-attention --autolaunch --allow-code --deepdanbooru  --disable-safe-unpickle --xformers  --force-enable-xformers --api

**Comment by wfjsw** [comment]
我觉得这是两个问题。

关于 API 不能用的问题：

```python
WebUIApi(url="http://127.0.0.1:7861")
```

这个端口疑似填错了，考虑到没有单独指定端口，截图里我也看不到现在的端口是什么。

上边那个报错昨天我在一个没开 API 的人那里看到了一例，没发现有什么问题，也不影响使用。

**Comment by HideUsSaveUs** [comment]
set COMMANDLINE_ARGS=--opt-split-attention --autolaunch --allow-code --deepdanbooru  --disable-safe-unpickle --xformers  --force-enable-xformers --api

**Comment by wfjsw** [comment]
正常端口是 7860 可以改过来再试试。

**Comment by HideUsSaveUs** [comment]
现在就是7860

**Comment by wfjsw** [comment]
你的py脚本里写了个7861啊

**Comment by HideUsSaveUs** [comment]
怪。我找找看

**Comment by HideUsSaveUs** [comment]
![image](https://user-images.githubusercontent.com/39188665/205476648-60583338-1624-4f5c-9401-2241bb2defc7.png)


```
[Running] set PYTHONIOENCODING=utf8 && python "c:\Users\HideUsSaveUs\Desktop\1.py"
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\HideUsSaveUs\Desktop\1.py", line 34, in <module>
    WebUIApi(url="http://127.0.0.1:7860").txt2img(payload=payload,outpath="1145.png",infotie=True)
  File "c:\Users\HideUsSaveUs\Desktop\1.py", line 14, in txt2img
    response = requests.post(url=f'{self.url}/sdapi/v1/txt2img', data=payload_json).json()
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

[Done] exited with code=1 in 0.668 seconds

```

**Comment by HideUsSaveUs** [comment]
不是端口的问题

**Comment by wfjsw** [comment]
日志能不能稍微网上翻一翻，我看下上边是怎么样的

**Comment by HideUsSaveUs** [comment]
![image](https://user-images.githubusercontent.com/39188665/205479509-31a2d936-3232-427d-a11d-58c85c825ad5.png)

**Comment by wfjsw** [comment]
为什么把 TLS 打开了？？？
装了什么插件？

**Comment by HideUsSaveUs** [comment]
![image](https://user-images.githubusercontent.com/39188665/205480091-ff10cc88-2e3c-4299-a22e-0729be3bf2bb.png)

**Comment by wfjsw** [comment]
这个 auto-tls-https 建议卸了，然后再试一试

**Comment by HideUsSaveUs** [comment]
这下docs打不开了,神神秘秘的但是api能用了


```
PS E:\AI色图\stable-diffusion-webui> .\webui.bat
venv "E:\AI色图\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Commit hash: 4b3c5bc24bffdf429c463a465763b3077fe55eb8
Installing requirements for Web UI
Launching Web UI with arguments: --opt-split-attention --autolaunch --allow-code --deepdanbooru --disable-safe-unpickle --xformers --force-enable-xformers --api
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [6569e224] from E:\AI色图\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0.ckpt
Using VAE found similar to selected model: E:\AI色图\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0.vae.ptLoading VAE weights from: E:\AI色图\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0.vae.pt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 22 textual inversion embeddings.
Embeddings: azusa, gbf, jazzjack, keta-nsfw, keta, koharu, lls-2000, lls-2500, lls-3000, lls-3500, lls-4000, lls-4500, lls-5000, mika, miyu, modare-3000, modare, shiro and schwi, wang yue, 望月, 雨伞, 雨傘ゆん-57000
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HideUsSaveUs\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
 15%|████████████▍                                                                      | 3/20 [00:13<01:19,  4.70s/it]WARNING:  Invalid HTTP request received.                                                 | 3/20 [00:08<00:55,  3.25s/it]
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
 45%|█████████████████████████████████████▎                                             | 9/20 [00:57<01:20,  7.31s/it]
Total progress:  45%|██████████████████████████████▏                                    | 9/20 [00:52<01:18,  7.16s/it]
```

**Comment by HideUsSaveUs** [comment]
要不还是无脑nowebui吧

**Comment by wfjsw** [comment]
docs 打不开是因为你浏览器现在还在 https 吧

**Comment by HideUsSaveUs** [comment]
思
